vscode:
  extensions:
    - alexkrechik.cucumberautocomplete
    - codezombiech.gitignore
    - redhat.java@1.22.1
    - vscjava.vscode-maven@0.42.0
    - vscjava.vscode-java-dependency@0.23.1
    - vscjava.vscode-java-pack@0.25.14
    - vscjava.vscode-java-debug@0.54.0
    - vscjava.vscode-java-test@0.39.1
    - anwar.papyrus-pdf